POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley",
    "lastName" : "Hughes",
    "email" : "aWeaver@test.com",
    "favoriteColor" : "Brown",
    "birthday" : "06/19/2000"
}